server:
  # 代理服务器启动的地址与端口配置
  host: "127.0.0.1"
  port: "33445"

database:
  # 数据库类型暂时不可改变
  type: "sqlite"
  path: "proxychain.db"

hunter:
  # 鹰图key 只需要积分即可
  apiKet: ""
fofa:
  # fofa key需要为高级会员，或有足够的积分
  apiKey: ""

config:
  # 精确地区代理，请求中国的地址使用中国的代理，如果是国外的地址则使用国外的代理
  preciseArea: false
  # 获取代理的模式，现有可选模式：priority（优先级）、random（随机）
  obtainingProxyMode: "random"
  # 数据库中最少代理数量的阈值
  miniProxyCount: 80
  # 定时任务执行间隔，单位秒
  taskTime: 60
  # 可信度每次减少的值
  priorityDownNum: 10
  # 可信度每次增加的值
  priorityUpNum: 2

